[package]
name = "shock"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bstr = { version = "1.6.2", default-features = false }
clap = { version = "4.4.2", features = ["derive"] }
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
toml = { version = "0.7.7", default-features = false, features = ["parse"] }
