name: Update flake dependencies

on:
  workflow_dispatch: # for allowing manual triggers of the workflow
  schedule:
    - cron: '37 16 3 * *'

permissions:
  contents: read

jobs:
  update-and-push-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v10
    - uses: DeterminateSystems/update-flake-lock@v21
      name: Update flake.lock
      id: flakeupdate
      with:
        token: ${{ secrets.RELEASE_PLZ_TOKEN }}
        branch: "automation/flake-update"
        commit-msg: "chore(flake): Update flake.lock"
        pr-title: "Update flake.lock"
        pr-labels: |
          automated
          dependencies
          flake update
    - name: Enable Pull Request Automerge
      run: gh pr merge --rebase --delete-branch --auto ${{ steps.flakeupdate.outputs.pull-request-number }}
      env:
        GH_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
